[package]
authors = ["Jason Ozias <jason.g.ozias@gmail.com>"]
categories = ["development-tools", "development-tools::build-utils"]
description = "Output vergen information in a formatted manner"
documentation = "https://docs.rs/vergen-pretty"
edition = "2024"
keywords = ["cargo", "instructions", "build", "tool"]
license = "MIT OR Apache-2.0"
rust-version = "1.96.0"
name = "vergen-pretty"
repository = "https://github.com/rustyhorde/vergen"
version = "10.0.3"

[package.metadata.cargo-matrix]
[[package.metadata.cargo-matrix.channel]]
name = "default"
always_deny = ["unstable"]
always_include = ["__vergen_test"]
include_optional = ["rkyv", "serde"]

[[package.metadata.cargo-matrix.channel]]
name = "nightly"
always_deny = []
always_include = ["__vergen_test", "unstable"]
include_optional = ["rkyv", "serde"]

[[package.metadata.cargo-matrix.channel]]
name = "nightly-empty"
always_deny = []
always_include = ["__vergen_empty_test", "unstable"]
include_optional = ["rkyv", "serde"]

[features]
default = []
unstable = ["vergen-gix/unstable"]
color = ["console"]
header = ["console", "rand"]
rkyv = ["dep:rkyv"]
trace = ["tracing"]
__vergen_test = ["vergen-gix", "vergen-gix/unstable"]
__vergen_empty_test = ["vergen-gix", "vergen-gix/unstable"]

[dependencies]
anyhow = { workspace = true }
bon = { workspace = true }
console = { workspace = true, optional = true }
convert_case = { workspace = true }
rand = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
rkyv = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }

[build-dependencies]
anyhow = { workspace = true }
rustversion = { workspace = true }
vergen-gix = { workspace = true, features = [
    "build",
    "cargo",
    "rustc",
    "si",
], optional = true }

[dev-dependencies]
regex = { workspace = true }
serde_json = { workspace = true }
tracing-subscriber = { workspace = true }

[package.metadata.docs.rs]
features = ["color", "header", "rkyv", "serde", "trace"]
rustdoc-args = ["--cfg", "docsrs"]
