on:
  workflow_run:
    workflows: [🦀 vergen 🦀]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

name: 🦀 vergen-lib 🦀

jobs:
  rustfmt:
    name: 📌 Formatting 📌
    uses: rustyhorde/workflows/.github/workflows/rustfmt.yml@main

  lints-linux:
    name: 🕳️ Clippy (Linux) 🕳️
    needs: rustfmt
    uses: rustyhorde/workflows/.github/workflows/clippy-all-features.yml@main
    with:
      os: ubuntu-latest
      channel: nightly
      target: x86_64-unknown-linux-gnu
      update: true
      project: vergen-lib

  lints-macos:
    name: 🕳️ Clippy (MacOS) 🕳️
    needs: rustfmt
    uses: rustyhorde/workflows/.github/workflows/clippy-all-features.yml@main
    with:
      os: macos-latest
      channel: nightly
      target: x86_64-apple-darwin
      update: true
      project: vergen-lib

  lints-windows:
    name: 🕳️ Clippy (Windows) 🕳️
    needs: rustfmt
    uses: rustyhorde/workflows/.github/workflows/clippy-all-features.yml@main
    with:
      os: windows-latest
      channel: nightly
      target: x86_64-pc-windows-gnu
      update: true
      project: vergen-lib

  test-linux:
    name: 🧪 Test (Linux) 🧪
    needs: lints-linux
    strategy:
      matrix:
        os: [ubuntu-latest]
        channel: ["1.73.0", "stable", "beta", "nightly"]
        target: [x86_64-unknown-linux-gnu]
    uses: rustyhorde/workflows/.github/workflows/test-all-features.yml@main
    with:
      os: ${{ matrix.os }}
      channel: ${{ matrix.channel }}
      target: ${{ matrix.target }}
      update: true
      project: vergen-lib

  test-macos:
    name: 🧪 Test (MacOS) 🧪
    needs: lints-macos
    strategy:
      matrix:
        os: [macos-latest]
        channel: ["1.73.0", "stable", "beta", "nightly"]
        target: [x86_64-apple-darwin]
    uses: rustyhorde/workflows/.github/workflows/test-all-features.yml@main
    with:
      os: ${{ matrix.os }}
      channel: ${{ matrix.channel }}
      target: ${{ matrix.target }}
      update: true
      project: vergen-lib

  test-windows-gnu:
    name: 🧪 Test (Windows - GNU) 🧪
    needs: lints-windows
    strategy:
      matrix:
        os: [windows-latest]
        channel: ["1.73.0", "stable", "beta", "nightly"]
        target: [x86_64-pc-windows-gnu]
    uses: rustyhorde/workflows/.github/workflows/test-all-features.yml@main
    with:
      os: ${{ matrix.os }}
      channel: ${{ matrix.channel }}
      target: ${{ matrix.target }}
      update: true
      project: vergen-lib

  test-windows-msvc:
    name: 🧪 Test (Windows - MSVC) 🧪
    needs: lints-windows
    strategy:
      matrix:
        os: [windows-latest]
        channel: ["1.73.0", "stable", "beta", "nightly"]
        target: [x86_64-pc-windows-msvc]
    uses: rustyhorde/workflows/.github/workflows/test-all-features.yml@main
    with:
      os: ${{ matrix.os }}
      channel: ${{ matrix.channel }}
      target: ${{ matrix.target }}
      update: true
      project: vergen-lib

  coverage-linux:
    name: 🧱 Coverage (Linux) 🧱
    needs: test-linux
    uses: rustyhorde/workflows/.github/workflows/coverage.yml@main
    with:
      os: ubuntu-latest
      channel: nightly
      target: x86_64-unknown-linux-gnu
      lcov: true
      html: true
      run_cmd: ${{ vars.VERGEN_LIB_RUN_CMD }}
    secrets: inherit

  coverage-macos:
    name: 🧱 Coverage (MacOS) 🧱
    needs: test-macos
    uses: rustyhorde/workflows/.github/workflows/coverage.yml@main
    with:
      os: macos-latest
      channel: nightly
      target: x86_64-apple-darwin
      lcov: true
      html: true
      run_cmd: ${{ vars.VERGEN_LIB_RUN_CMD }}
    secrets: inherit

  coverage-windows:
    name: 🧱 Coverage (Wndows) 🧱
    needs: [test-windows-gnu, test-windows-msvc]
    strategy:
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-pc-windows-msvc]
    uses: rustyhorde/workflows/.github/workflows/coverage.yml@main
    with:
      os: windows-latest
      channel: nightly
      target: ${{ matrix.target }}
      lcov: true
      html: true
      run_cmd: ${{ vars.VERGEN_LIB_RUN_CMD }}
    secrets: inherit
