on:
  workflow_call:

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

name: 🦀 vergen-git2 🦀

jobs:
  rustfmt:
    name: 📌 Formatting 📌
    # main
    uses: rustyhorde/workflows/.github/workflows/rustfmt.yml@7a073ab416038755f63ff549d1331c9644d37cd7

  lints-linux:
    name: 🕳️ Clippy (Linux) 🕳️
    needs: rustfmt
    # main
    uses: rustyhorde/workflows/.github/workflows/clippy-all-features.yml@7a073ab416038755f63ff549d1331c9644d37cd7
    with:
      os: ubuntu-latest
      channel: nightly
      target: x86_64-unknown-linux-gnu
      update: true
      project: vergen-git2

  lints-macos:
    name: 🕳️ Clippy (MacOS) 🕳️
    needs: rustfmt
    # main
    uses: rustyhorde/workflows/.github/workflows/clippy-all-features.yml@7a073ab416038755f63ff549d1331c9644d37cd7
    with:
      os: macos-latest
      channel: nightly
      target: apple-darwin
      update: true
      project: vergen-git2

  lints-windows:
    name: 🕳️ Clippy (Windows) 🕳️
    needs: rustfmt
    # main
    uses: rustyhorde/workflows/.github/workflows/clippy-all-features.yml@7a073ab416038755f63ff549d1331c9644d37cd7
    with:
      os: windows-latest
      channel: nightly
      target: x86_64-pc-windows-gnu
      update: true
      project: vergen-git2

  test-linux:
    name: 🧪 Test (Linux) 🧪
    needs: lints-linux
    strategy:
      matrix:
        os: [ubuntu-latest]
        channel: ["1.96.0", "stable", "beta", "nightly"]
        target: [x86_64-unknown-linux-gnu]
    # main
    uses: rustyhorde/workflows/.github/workflows/test-all-features.yml@7a073ab416038755f63ff549d1331c9644d37cd7
    with:
      os: ${{ matrix.os }}
      channel: ${{ matrix.channel }}
      target: ${{ matrix.target }}
      update: true
      project: vergen-git2

  test-macos:
    name: 🧪 Test (MacOS) 🧪
    needs: lints-macos
    strategy:
      matrix:
        os: [macos-latest]
        channel: ["1.96.0", "nightly"]
        target: [apple-darwin]
    # main
    uses: rustyhorde/workflows/.github/workflows/test-all-features.yml@7a073ab416038755f63ff549d1331c9644d37cd7
    with:
      os: ${{ matrix.os }}
      channel: ${{ matrix.channel }}
      target: ${{ matrix.target }}
      update: true
      project: vergen-git2

  test-windows-gnu:
    name: 🧪 Test (Windows - GNU) 🧪
    needs: lints-windows
    strategy:
      matrix:
        os: [windows-latest]
        channel: ["1.96.0", "nightly"]
        target: [x86_64-pc-windows-gnu]
    # main
    uses: rustyhorde/workflows/.github/workflows/test-all-features.yml@7a073ab416038755f63ff549d1331c9644d37cd7
    with:
      os: ${{ matrix.os }}
      channel: ${{ matrix.channel }}
      target: ${{ matrix.target }}
      update: true
      project: vergen-git2

  test-windows-msvc:
    name: 🧪 Test (Windows - MSVC) 🧪
    needs: lints-windows
    strategy:
      matrix:
        os: [windows-latest]
        channel: ["1.96.0", "nightly"]
        target: [x86_64-pc-windows-msvc]
    # main
    uses: rustyhorde/workflows/.github/workflows/test-all-features.yml@7a073ab416038755f63ff549d1331c9644d37cd7
    with:
      os: ${{ matrix.os }}
      channel: ${{ matrix.channel }}
      target: ${{ matrix.target }}
      update: true
      project: vergen-git2

  coverage-linux:
    name: 🧱 Coverage (Linux) 🧱
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    needs: test-linux
    # main
    uses: rustyhorde/workflows/.github/workflows/coverage.yml@7a073ab416038755f63ff549d1331c9644d37cd7
    with:
      os: ubuntu-latest
      channel: nightly
      target: x86_64-unknown-linux-gnu
      lcov: true
      html: true
      run_cmd: ${{ vars.VERGEN_GIT2_RUN_CMD }}
    secrets: inherit

  coverage-macos:
    name: 🧱 Coverage (MacOS) 🧱
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    needs: test-macos
    # main
    uses: rustyhorde/workflows/.github/workflows/coverage.yml@7a073ab416038755f63ff549d1331c9644d37cd7
    with:
      os: macos-latest
      channel: nightly
      target: apple-darwin
      lcov: true
      html: true
      run_cmd: ${{ vars.VERGEN_GIT2_RUN_CMD }}
    secrets: inherit

  coverage-windows:
    name: 🧱 Coverage (Wndows) 🧱
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    needs: [test-windows-gnu, test-windows-msvc]
    strategy:
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-pc-windows-msvc]
    # main
    uses: rustyhorde/workflows/.github/workflows/coverage.yml@7a073ab416038755f63ff549d1331c9644d37cd7
    with:
      os: windows-latest
      channel: nightly
      target: ${{ matrix.target }}
      lcov: true
      html: true
      run_cmd: ${{ vars.VERGEN_GIT2_RUN_CMD }}
    secrets: inherit
